#pragma once

#define PERMISSIVE_HOLD
//#define IGNORE_MOD_TAP_INTERRUPT
#define LEADER_TIMEOUT 500
#define LEADER_PER_KEY_TIMING 350
#define TAPPING_TERM 280
// #define TAP_CODE_DELAY 20
#define USB_POLLING_INTERVAL_MS 5

